#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

MONCOUNT=$( xrandr -q | grep "connected" | grep -v "disconnected" | wc | cut -d" " -f 7 )
if [ $MONCOUNT -eq 2 ]; then
	bspc monitor primary -d 1 2 3 4 5
	bspc monitor HDMI-A-0 -d 6 7 8 9 10
else
	bspc monitor primary -d 1 2 3 4 5 6 7 8 9 10

fi

bspc config border_width	4
bspc config window_gap		12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

~/.config/lemonbar/init | lemonbar -p &

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
