version: "2"

checks:
  method-count:
    config:
      threshold: 50

engines:
  golint:
    enabled: true
    checks:
      GoLint/Comments/DocComments:
        enabled: false
  gofmt:
    enabled: true
  govet:
    enabled: true
